version: '3.7'

services:
  traefik:
    image: traefik:3.0
    ports:
      - 80:80 # HTTP port
    restart: always
    labels:
      # Traefik configuration
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.services.traefik-dashboard.loadbalancer.server.port=8080

      # HTTP router configuration
      - traefik.http.routers.traefik-dashboard-http.entrypoints=http
      - traefik.http.routers.traefik-dashboard-http.rule=PathPrefix(`/dashboard`)

      # HTTP Basic Auth middleware (Optional for local development)
      # Uncomment these lines if you want to secure the dashboard with basic auth.
      # - traefik.http.middlewares.admin-auth.basicauth.users=${USERNAME}:${HASHED_PASSWORD}
      # - traefik.http.routers.traefik-dashboard-http.middlewares=admin-auth

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Docker socket for reading service labels
      - traefik-public-certificates:/certificates # Keep this if required in the future
    command:
      # Docker provider configuration
      - --providers.docker
      - --providers.docker.exposedbydefault=false

      # Entrypoints configuration
      - --entrypoints.http.address=:80

      # Logging and API configuration
      - --accesslog
      - --log
      - --api.dashboard=true
      - --api.insecure=true # Enable insecure mode for easy access during local development
    networks:
      - traefik-public

volumes:
  traefik-public-certificates: # Persistent volume for certificates

networks:
  traefik-public:
    external: false # Create a new local network for development
